#!/usr/bin/env python3
"""Convert the MAME 'rallyx' ROM set into a C header for SMOKESCREEN.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

MAIN = [('1b', 0x1000), ('rallyxn.1e', 0x1000), ('rallyxn.1h', 0x1000), ('rallyxn.1k', 0x1000)]
GFX  =  ('8e', 0x1000)          # characters and sprites share one 4 KB ROM
DOTS =  ('rx1-6.8m', 0x100)     # the radar dots and the smoke
PAL  =  ('rx1-1.11n', 0x20)     # 32 colours
LUT  =  ('rx1-7.8p', 0x100)     # colour lookup: (colour, pixel) -> palette entry
WAVE =  ('rx1-5.3p', 0x100)     # 8 WSG waveforms of 32 samples

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'rallyx')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    rom = b''.join(load(romdir, n, s) for n, s in MAIN)
    out = ['/* rallyx_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef RALLYX_ROMS_H', '#define RALLYX_ROMS_H', '#include <stdint.h>', '',
           c_array('rx_rom',  rom,                       '[0x4000]'), '',
           c_array('rx_gfx',  load(romdir, *GFX),        '[0x1000]'), '',
           c_array('rx_dots', load(romdir, *DOTS),       '[0x100]'), '',
           c_array('rx_pal',  load(romdir, *PAL),        '[0x20]'), '',
           c_array('rx_lut',  load(romdir, *LUT),        '[0x100]'), '',
           c_array('rx_wave', load(romdir, *WAVE),       '[0x100]'), '',
           '#endif']
    (outdir / 'rallyx_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "rallyx_roms.h"}')

if __name__ == '__main__':
    main()
